from typing import Dict, List

COMMAND_DEFS: Dict[str, Dict] = {
    "ask": {
        "hide": "break",
        "help": "ASK <name> about a topic, or ASK without a topic to list what they discuss.",
        "slots": [
            {"category": "npcs", "separator": " about "},
            {"category": "topics", "separator": " ", "context": {"collection": "ask_topics", "source_slot": 0}},
        ],
        "aliases": [],
    },
    "ask about": {
        "hide": "break",
        "help": "ASK <name> ABOUT <topic>. Ask a person without a topic to list what they will discuss.",
        "slots": [
            {"category": "npcs", "separator": " about "},
            {"category": "topics", "separator": " ", "context": {"collection": "ask_topics", "source_slot": 0}},
        ],
        "aliases": [],
    },
    "assess": {
        "hide": "preserve",
        "help": "ASSESS <target> sizes up a person or thing before you act.",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "attack": {
        "hide": "special",
        "help": "ATTACK <name> (courage-based; killing notable figures shifts influence).",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "bond": {
        "hide": "break",
        "help": "BOND <name> shares a meal to build friendship.",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "bribe": {
        "hide": "break",
        "help": "BRIBE <npc> offers money to change an outcome.",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "buy from": {
        "hide": "break",
        "help": "BUY FROM <vendor> to purchase items from NPCs.",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "claim": {
        "hide": "break",
        "help": "CLAIM makes this safe room your safehouse.",
        "slots": [],
        "aliases": [],
    },
    "disguise as": {
        "hide": "break",
        "help": "DISGUISE AS <faction role> to pass as one of them.",
        "slots": [{"category": "disguises", "separator": " "}],
        "aliases": [],
    },
    "drop": {
        "hide": "break",
        "help": "DROP <item>, or bare DROP to choose from a chooser.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": ["discard"],
    },
    "eat": {
        "hide": "break",
        "help": "EAT opens a chooser of food you carry.",
        "slots": [],
        "aliases": [],
    },
    "equip": {
        "hide": "break",
        "help": "EQUIP <item> readies a held weapon or wears armour.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": ["wear"],
    },
    "examine": {
        "hide": "preserve",
        "help": "EXAMINE <npc/item> for detail and what you can do with it.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": [],
    },
    "favor": {
        "hide": "break",
        "help": "FAVOR <npc> asks someone to do you a good turn.",
        "slots": [],
        "aliases": [],
    },
    "give": {
        "hide": "break",
        "help": "GIVE <item> TO <name>.",
        "slots": [{"category": "inventory_items", "separator": " to "}, {"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "go": {
        "hide": "special",
        "help": "GO <direction> (n/s/e/w/u/d), or GO <room name> to auto-walk. Follow the Routes line between districts.",
        "slots": [{"category": "exits", "separator": " "}],
        "aliases": ["move", "walk", "head"],
    },
    "help": {
        "hide": "preserve",
        "help": "HELP lists everything; HELP <command> shows how to use one; HELP START for the basics.",
        "slots": [],
        "aliases": ["h", "?"],
    },
    "hide": {
        "hide": "special",
        "help": "HIDE conceals you. Moving or loud actions break it.",
        "slots": [],
        "aliases": [],
    },
    "inventory": {
        "hide": "preserve",
        "help": "INVENTORY (i) lists what you carry, each with its use.",
        "slots": [],
        "aliases": [],
    },
    "journal": {
        "hide": "preserve",
        "help": "JOURNAL shows your journal; JOURNAL <name> reads an archived journal.",
        "slots": [],
        "aliases": [],
    },
    "leave note": {
        "hide": "break",
        "help": "LEAVE NOTE drops a written note in the room.",
        "slots": [],
        "aliases": [],
    },
    "look": {
        "hide": "preserve",
        "help": "LOOK, or EXAMINE <npc/item> for detail and what you can do with it.",
        "slots": [],
        "aliases": [],
    },
    "memorial": {
        "hide": "preserve",
        "help": "MEMORIAL shows the legacy book of fallen characters.",
        "slots": [],
        "aliases": [],
    },
    "missions": {
        "hide": "preserve",
        "help": "MISSIONS shows active work; MISSIONS AVAILABLE lists jobs; MISSIONS COMPLETE/ABANDON <id>.",
        "slots": [],
        "aliases": [],
    },
    "mod weapon": {
        "hide": "break",
        "help": "MOD WEAPON <weapon> WITH <mod> attaches a modification to a weapon.",
        "slots": [],
        "aliases": [],
    },
    "open": {
        "hide": "break",
        "help": "OPEN <container> is the only way to unlock a locked container.",
        "slots": [{"category": "containers", "separator": " "}],
        "aliases": [],
    },
    "pickpocket": {
        "hide": "break",
        "help": "PICKPOCKET <name> (risky; raises suspicion if caught).",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "plant": {
        "hide": "break",
        "help": "PLANT <item> ON <name> to frame them.",
        "slots": [],
        "aliases": [],
    },
    "quit": {
        "hide": "preserve",
        "help": "QUIT saves and exits.",
        "slots": [],
        "aliases": ["exit", "logout", "bye", "q"],
    },
    "read": {
        "hide": "break",
        "help": "READ <item>, or bare READ to choose from a chooser.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": [],
    },
    "remove": {
        "hide": "break",
        "help": "REMOVE <armour>.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": [],
    },
    "repair": {
        "hide": "break",
        "help": "REPAIR <weapon>, or bare REPAIR to choose a weapon.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": [],
    },
    "retrieve": {
        "hide": "break",
        "help": "RETRIEVE gear stashed at your safehouse.",
        "slots": [],
        "aliases": [],
    },
    "rumors": {
        "hide": "preserve",
        "help": "RUMORS shows the rumours reaching you about the city.",
        "slots": [],
        "aliases": [],
    },
    "rumours": {
        "hide": "preserve",
        "help": "RUMOURS shows the rumours reaching you about the city.",
        "slots": [],
        "aliases": [],
    },
    "say": {
        "hide": "break",
        "help": "SAY <message> speaks aloud to the room.",
        "slots": [],
        "aliases": [],
    },
    "search": {
        "hide": "break",
        "help": "SEARCH <detail> reveals hidden items or dead drops into the room.",
        "slots": [],
        "aliases": [],
    },
    "season": {
        "hide": "preserve",
        "help": "SEASON tells the current season and what it brings.",
        "slots": [],
        "aliases": [],
    },
    "sell": {
        "hide": "break",
        "help": "SELL <item>, or bare SELL to choose from a chooser.",
        "slots": [{"category": "inventory_items", "separator": " "}],
        "aliases": [],
    },
    "skip tutorial": {
        "hide": "preserve",
        "help": "SKIP TUTORIAL leaves the tutorial early.",
        "slots": [],
        "aliases": [],
    },
    "sound": {
        "hide": "preserve",
        "help": "SOUND shows the sounds around you.",
        "slots": [],
        "aliases": [],
    },
    "status": {
        "hide": "preserve",
        "help": "STATUS shows your condition, objective, season, and the Liberation influence tide.",
        "slots": [],
        "aliases": ["stat"],
    },
    "stop": {
        "hide": "preserve",
        "help": "STOP TAIL ends an active tail.",
        "slots": [{"category": "stop_targets", "separator": " "}],
        "aliases": [],
    },
    "tail": {
        "hide": "break",
        "help": "TAIL <name> follows someone secretly.",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "take": {
        "hide": "break",
        "help": "TAKE <item>, or bare TAKE to choose from a chooser.",
        "slots": [{"category": "take_items", "separator": " "}],
        "aliases": ["get", "grab"],
    },
    "take from": {
        "hide": "break",
        "help": "TAKE <item> FROM <container>, or use the open container panel.",
        "slots": [{"category": "items", "separator": " from "}, {"category": "containers", "separator": " "}],
        "aliases": [],
    },
    "talk to": {
        "hide": "break",
        "help": "TALK TO <name> greets someone and shows what to ASK them about.",
        "slots": [{"category": "npcs", "separator": " "}],
        "aliases": [],
    },
    "trust": {
        "hide": "preserve",
        "help": "TRUST shows how each faction regards you.",
        "slots": [],
        "aliases": [],
    },
    "unhide": {
        "hide": "special",
        "help": "UNHIDE stops hiding.",
        "slots": [],
        "aliases": [],
    },
    "wanted": {
        "hide": "preserve",
        "help": "WANTED shows your standing with the authorities.",
        "slots": [],
        "aliases": [],
    },
    "whisper": {
        "hide": "break",
        "help": "WHISPER <name> <message>.",
        "slots": [{"category": "players", "separator": " "}],
        "aliases": [],
    },
    "write note": {
        "hide": "break",
        "help": "WRITE NOTE <text> creates a note; TAKE NOTE <text> also works.",
        "slots": [],
        "aliases": [],
    },
    "yell": {
        "hide": "break",
        "help": "YELL <message> broadcasts to nearby rooms, and draws attention.",
        "slots": [],
        "aliases": [],
    },
}
