CURFEW_MINUTE = 1260
EVENT_LOG_MAXLEN = 500
WORLD_EVENTS_MAXLEN = 50
CONVERSATION_HISTORY_MAXLEN = 20
NPC_MEMORY_MAXLEN = 30
HUNGER_DECAY_RATE = 1.2
HUNGER_HEALTH_DAMAGE = 2
LOW_HUNGER_THRESHOLD = 20
STATE_BROADCAST_INTERVAL = 5

EVENTS_PATH = "server/data/events.yaml"
TRUST_RULES_PATH = "server/data/trust_rules.yaml"
DISGUISES_PATH = "server/data/disguises.yaml"
STORYLETS_PATH = "server/data/storylets.yaml"
OBITUARY_PATH = "server/data/obituary_templates.yaml"
BACKGROUNDS_PATH = "server/data/character)backgrounds.yaml"
MISSIONS_PATH = "server/data/missions.yaml"

BASE_COURAGE_RANGE = (30, 50)
AUTHORITY_CIVILIAN_RANGE = (5, 20)
AUTHORITY_SOLDIER_RANGE = (40, 60)
AUTHORITY_KEMPEITAI_RANGE = (60, 85)
DISARM_CHANCE_CAP = 80
STEALTH_KILL_BONUS = 25

HUNGER_DECAY_PER_HOUR = 3
HEALTH_DECAY_HUNGRY = 2
MORALE_DECAY_PER_HOUR = 1

STAT_GAIN_COURAGE_COMBAT = 1
STAT_GAIN_STEALTH_HIDE = 1
STAT_GAIN_STEALTH_TAIL = 1
STAT_GAIN_SUCCESSFUL_TAIL = 1
STAT_CAP = 100
MORALE_LOW_THRESHOLD = 30
MORALE_PENALTY_MAX = 20
COMBAT_GROWTH_FACTIONS = ("kempeitai", "gmd", "green_gang")

TRUST_DECAY_PER_DAY = 2
BETRAYAL_PENALTY = 15
BETRAYAL_SPREAD_DAYS = 3

RICE_BOWL_COST = 2
BAOZI_COST = 1
TEA_COST = 1
PICKPOCKET_BASE = 5
MISSION_FABI_RANGE = (10, 50)
NURSE_COST = 20
NURSE_HEAL = 30

CURFEW_START_HOUR = 20
CURFEW_END_HOUR = 6

DAY_LIBERATION = 2835
INFLUENCE_THRESHOLD = 80
UNITY_RANGE = 15

WEATHER_RAIN_CHANCE = {30: 30, 10: 10}
WEATHER_CHANGE_INTERVAL = 60
DEGRADE_RAIN_RATE = 1