from collections import Counter, defaultdict, deque
from dataclasses import dataclass
import json
import os

DISTRICT_OF = {
    "bund_dawn": "Bund",
    "bund_canton_road": "Bund",
    "customs_house": "Bund",
    "hsbc_building": "Bund",
    "tea_house": "Bund",
    "international_settlement_bar": "Bund",
    "checkpoint_garden_bridge": "Bund",
    "gmd_safehouse_bund": "Bund",
    "bund_river_promenade": "Bund",
    "holy_trinity_cathedral": "Bund",
    "bund_hankow_road": "Bund",
    "astor_house_alley": "Bund",
    "nanjing_road": "Nanjing Road",
    "sincere_department_store": "Nanjing Road",
    "wing_on_company": "Nanjing Road",
    "broadway_warehouses": "Nanjing Road",
    "sun_sun_store": "Nanjing Road",
    "checkpoint_soochow_creek": "Nanjing Road",
    "umbrella_market": "Nanjing Road",
    "velvet_nightclub": "Nanjing Road",
    "commercial_black_market": "Nanjing Road",
    "commercial_printshop": "Nanjing Road",
    "commercial_watchmaker": "Nanjing Road",
    "commercial_gang_office": "Nanjing Road",
    "yuyuan_garden_gate": "Old City",
    "city_god_temple": "Old City",
    "tortoise_shell_alley": "Old City",
    "yuyuan_rear_lanes": "Old City",
    "grey_brick_longtang": "Old City",
    "old_city_market": "Old City",
    "st_josephs_nanshi": "Old City",
    "gmd_safehouse_old_city": "Old City",
    "old_city_tea_room": "Old City",
    "laundry_line_courtyard": "Old City",
    "persimmon_tree_courtyard": "Old City",
    "old_city_clinic": "Old City",
    "old_city_market_stall": "Old City",
    "checkpoint_north_gate": "Hongkou",
    "hongkou_checkpoint_square": "Hongkou",
    "wayside_road": "Hongkou",
    "japanese_bathhouse_lane": "Hongkou",
    "dobun_shoin_academy_gate": "Hongkou",
    "dobun_shoin_academy": "Hongkou",
    "kempeitai_hq": "Hongkou",
    "university": "Hongkou",
    "hongkou_field_hospital": "Hongkou",
    "hongkou_refugee_block": "Hongkou",
    "little_tokyo_row_houses": "Hongkou",
    "seward_road_tenements": "Hongkou",
    "hongkou_detention": "Hongkou",
    "avenue_joffre_market": "French Concession",
    "rue_lafayette": "French Concession",
    "cercle_sportif_francais": "French Concession",
    "plane_tree_avenue": "French Concession",
    "rue_du_consulat_gardens": "French Concession",
    "french_concession_safehouse": "French Concession",
    "french_jazz_cafe": "French Concession",
    "french_consulate_office": "French Concession",
    "french_newspaper_office": "French Concession",
    "french_bakery": "French Concession",
    "glass_arcade": "French Concession",
    "eglise_saint_pierre": "French Concession",
    "customs_house_jetty": "Yangpu",
    "jardine_matheson_wharf": "Yangpu",
    "nanshi_fishermans_pier": "Yangpu",
    "imperial_army_wharf": "Yangpu",
    "dock_warehouse": "Yangpu",
    "warehouse_district": "Yangpu",
    "docks_cargo_berth": "Yangpu",
    "mission_supply_huozhan": "Yangpu",
    "nanshi_tea_duizhan": "Yangpu",
    "rue_montauban_silk_huozhan": "Yangpu",
    "yangshupu_factory_floor": "Yangpu",
    "printers_union_cellar": "Zhabei",
    "power_station_bunker": "Zhabei",
    "guerrilla_supply_cache": "Zhabei",
    "radio_communications_room": "Zhabei",
    "boone_road_school": "Zhabei",
    "mill_workers_night_school": "Zhabei",
    "chapei_ruins": "Zhabei",
    "mctyeire_school": "Xujiahui",
    "zikawei_cathedral": "Xujiahui",
    "church_refugee_clinic": "Xujiahui",
    "mctyeire_classroom": "Xujiahui",
    "zikawei_mission_chapel": "Xujiahui",
    "chungking_radio_station": "Xujiahui",
    "intelligence_bureau_annex": "Xujiahui",
    "hidden_altar_undercroft": "Xujiahui",
}